import 'package:bitin_coin_app/model/bitin_model.dart';

List<UserModel> friends = [
  UserModel(
    userName: 'Inderdeep Singh',
    userCoins: '100',
    userRefers: '20',
    userCoinMiningRate: '0.45',
    userIsActive: true,
    clickTime: DateTime.now(),
    userIsMining: true,
  ),
  UserModel(
    userName: 'Inderdeep Singh',
    userCoins: '100',
    userRefers: '20',
    userCoinMiningRate: '0.45',
    userIsActive: true,
    clickTime: DateTime.now(),
    userIsMining: true,
  ),
  UserModel(
    userName: 'Inderdeep Singh',
    userCoins: '100',
    userRefers: '20',
    userCoinMiningRate: '0.45',
    userIsActive: true,
    clickTime: DateTime.now(),
    userIsMining: true,
  ),
  UserModel(
    userName: 'Inderdeep Singh',
    userCoins: '100',
    userRefers: '20',
    userCoinMiningRate: '0.45',
    userIsActive: true,
    clickTime: DateTime.now(),
    userIsMining: true,
  ),
  UserModel(
    userName: 'Inderdeep Singh',
    userCoins: '100',
    userRefers: '20',
    userCoinMiningRate: '0.45',
    userIsActive: true,
    clickTime: DateTime.now(),
    userIsMining: true,
  ),
  UserModel(
    userName: 'Inderdeep Singh',
    userCoins: '100',
    userRefers: '20',
    userCoinMiningRate: '0.45',
    userIsActive: true,
    clickTime: DateTime.now(),
    userIsMining: true,
  ),
  UserModel(
    userName: 'Inderdeep Singh',
    userCoins: '100',
    userRefers: '20',
    userCoinMiningRate: '0.45',
    userIsActive: true,
    clickTime: DateTime.now(),
    userIsMining: true,
  ),
  UserModel(
    userName: 'Inderdeep Singh',
    userCoins: '100',
    userRefers: '20',
    userCoinMiningRate: '0.45',
    userIsActive: true,
    clickTime: DateTime.now(),
    userIsMining: true,
  ),
  UserModel(
    userName: 'Inderdeep Singh',
    userCoins: '100',
    userRefers: '20',
    userCoinMiningRate: '0.45',
    userIsActive: true,
    clickTime: DateTime.now(),
    userIsMining: true,
  ),
  UserModel(
    userName: 'Inderdeep Singh',
    userCoins: '100',
    userRefers: '20',
    userCoinMiningRate: '0.45',
    userIsActive: true,
    clickTime: DateTime.now(),
    userIsMining: true,
  ),
  UserModel(
    userName: 'Inderdeep Singh',
    userCoins: '100',
    userRefers: '20',
    userCoinMiningRate: '0.45',
    userIsActive: true,
    clickTime: DateTime.now(),
    userIsMining: true,
  ),
];
